### ISSUE TITLE
Make the bot join VC when requesting to play song

### ISSUE THREAD

**Issue by QuantumCoded** [Skarlett/coggie-bot#98]
`@Coggerz play <url>` should automatically run `@Coggerz join` as well to prevent users from having to rerun the play command.

**Comment by Skarlett** [comment]
Not immediately planned for, but something thats been on the back burner forever. We'll hold this open for anyone who wishes to contribute to the project.

**Comment by Skarlett** [comment]
Present in 1.4.15
