### ISSUE TITLE
Allow coggers to take a URL to a subsonic server.

### ISSUE THREAD

**Issue by QuantumCoded** [Skarlett/coggie-bot#99]
This would allow users to pass in a temporary ngrok link to their local subsonic server and play their local music collection through the bot.

**Comment by Skarlett** [comment]
@QuantumCoded 
Is ngrok a requirement, or will an ssh tunnel suffice? I'm thinking that connecting to `music@coggiebot.tld` over ssh, and piping an mp3 file down the pipe to be read would be the most rapid deployment option there is.

authenticated keys can be placed under `/var/lib/coggiebot/ssh/authorized_keys`, and then an unprivileged user without a shell can accept the download and give transaction notices.

we can have two users, `airsonic@coggiebot.tld` for the HTTP implementation, using a reverse tunnel, we listen on localhost and route traffic from the reverse tunnel into it.

while also having as a normal ssh `music@coggiebot.tld` where it accepts raw files.

**Comment by QuantumCoded** [comment]
@Skarlett
I think that accepting single files through scp/ssh is absolutely fine, just so long as the user gets the ability to add a server to coggie-bot allowing it to extend it's music library. The username should also probably be `subsonic` instead of `airsonic` as well to match the actual protocol name. My only concern was being able to do something like
`ssh -fN -R 55003:subsonic.lan:4040 subsonic@coggiebot.tld` and then `@Coggerz play Simanification` and get music over that ssh connection.

**Comment by Skarlett** [comment]
Added HTTP support in #175
